# Gopkg.toml
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true

[[override]]
  name = "github.com/tendermint/go-amino"
  source = "github.com/binance-chain/bnc-go-amino"
  version = "=v0.14.1-binance.1"

[[override]]
  name = "github.com/tendermint/iavl"
  source = "github.com/binance-chain/bnc-tendermint-iavl"
  version = "=v0.12.0-binance.0"

[[override]]
  name = "github.com/tendermint/tendermint"
  source = "github.com/binance-chain/bnc-tendermint"
  version = "=v0.29.1-binance.3"

[[constraint]]
  name = "github.com/cosmos/cosmos-sdk"
  source = "github.com/binance-chain/bnc-cosmos-sdk"
  version = "=v0.25.0-binance.6"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/Shopify/sarama"
  version = "1.17.0"

[[constraint]]
  name = "github.com/linkedin/goavro"
  version = "2.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/deathowl/go-metrics-prometheus"

[[override]]
  name = "golang.org/x/crypto"
  source = "https://github.com/tendermint/crypto"
  revision = "3764759f34a542a3aef74d6b02e35be7ab893bba"

# we use the secp256k1 implementation:
[[override]]
  name = "github.com/ethereum/go-ethereum"
  version = "^v1.8.21"

   # Prevent dep from pruning build scripts and codegen templates
   # note: this leaves the whole go-ethereum package in vendor
   # can be removed when https://github.com/golang/dep/issues/1847 is resolved
   [[prune.project]]
     name = "github.com/ethereum/go-ethereum"
     unused-packages = false

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/natefinch/lumberjack"
  version = "2.1.0"